apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
  namespace: test
spec:
  # service mesh provider can be: kubernetes, istio, appmesh, nginx, gloo
  provider: kubernetes
  # deployment reference
  ### 当前部署的新版本服务(可以是Deployment, 也可以是DaemonSet)
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  # the maximum time in seconds for the canary deployment
  # to make progress before rollback (default 600s)
  ### canary, primary部署超时时间.如果超过这个时间还没有部署好,则不会进行流量调整了
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  ### K8s原生的HPA
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: podinfo
  service:
    port: 9898
    portDiscovery: true
  ### 是否跳过metrcis分析. 如果为true, 相当于一次性将primary替换成canary service
  skipAnalysis: false
  analysis:
    # schedule interval (default 60s)
    ### 每次间隔30s
    interval: 30s
    # max number of failed checks before rollback
    ### 最多允许2次metrics验证失败.如果超过2次, 则进行回滚
    threshold: 2
    # number of checks to run before rollback
    ### 整个流程会执行10次
    iterations: 10
    # Prometheus checks based on 
    # http_request_duration_seconds histogram
    metrics:
      - name: request-success-rate
        # minimum req success rate (non 5xx responses)
        # percentage (0-100)
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        # maximum req duration P99
        # milliseconds
        thresholdRange:
          max: 500
        interval: 30s
    # acceptance/load testing hooks
    webhooks:
      - name: smoke-test
        type: pre-rollout
        url: http://flagger-loadtester.test/
        timeout: 15s
        metadata:
          type: bash
          cmd: "curl -sd 'test' http://podinfo-canary.test:9898/token | grep token"
      - name: load-test
        url: http://flagger-loadtester.test/
        timeout: 5s
        metadata:
          type: cmd
          cmd: "hey -z 1m -q 10 -c 2 http://podinfo-canary.test:9898/"
