name: clusternet

on:
  workflow_dispatch: 
  #schedule:
  #  - cron:  0 9,12,21 * * * 
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  clusternet:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    #- uses: actions/checkout@v2
    
    - name: clusternet
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         
         docker info 
         
         curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
         chmod +x ./kubectl
         mv ./kubectl /usr/local/bin/kubectl
         /usr/local/bin/kubectl version --client
         
         curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
         helm version --client
         
         KIND_VESION="v0.12.0"
         curl -Lo ./kind https://kind.sigs.k8s.io/dl/${KIND_VESION}/kind-linux-amd64
         chmod +x ./kind
         mv ./kind /usr/local/bin/kind
         kind version

         #wget https://raw.githubusercontent.com/clusternet/clusternet/main/hack/local-running.sh && \
         #     bash local-running.sh
         
         git clone https://github.com/clusternet/clusternet && cd clusternet
         ./hack/local-running.sh
         
         echo "==============================="
         
         kubectl config get-contexts
         
         echo "==============================="
         current_time=$(date +"%Y-%m-%d-%k")
         echo ${current_time}
         echo "==============================="
         
         kubectl get pod -n clusternet-system 
