name: k3s-cilium

on:
  workflow_dispatch: 
  #schedule:
  #  - cron:  0 9,12,21 * * * 
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  k3s-cilium:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    #- uses: actions/checkout@v2
    
    - name: k3s-cilium
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         
         set -eux
         
         red="\033[31m"
         green="\033[32m"
         yellow="\033[33m"
         white="\033[0m"
         
         echo "****** kubectl install *******"
         curl -sLO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/Linux/amd64/kubectl
         chmod +x ./kubectl
         mv ./kubectl /usr/local/bin/kubectl
         /usr/local/bin/kubectl version --client
         echo -e "${green}kubectl is already installed${white}"
         
         curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" \
              INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=10.42.0.0/16 --disable-network-policy --disable=traefik" sh -
         
         export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
         
         kubectl get po -A
         echo "****** k3s running *******"
         
         curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
         sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
         sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
         rm cilium-linux-amd64.tar.gz{,.sha256sum}
         
         cilium version
         
         cilium install
         
         cilium status
         
         kubectl get po -A
