name: kurator

on:
  workflow_dispatch: 
  #schedule:
  #  - cron:  0 9,12,21 * * * 
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  kurator:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.13.1'
    - name: Go version   
      run: go version  
        
    - name: kurator
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         
         git clone https://github.com/kurator-dev/kurator
         cd kurator
         make kurator
         
         echo "==============================="
         ls -l out

         echo "==============================="
         current_time=$(date +"%Y-%m-%d-%k")
         echo ${current_time}
         echo "==============================="
