name: terraform-huaweicloud

on:
  workflow_dispatch: 
  #schedule:
  #  - cron:  0 9,12,21 * * * 
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  terraform-huaweicloud:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
      ### uses: aws-actions/configure-aws-credentials@v1

    - name: Terraform version   
      run: terraform version  
        
    - name: terraform-huaweicloud
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         
         ## https://github.com/huaweicloud/terraform-provider-huaweicloud/releases

         
         ## mkdir -p ~/.terraform.d/plugins/local-registry/huaweicloud/huaweicloud/1.47.1/linux_amd64/
         ## cp terraform-provider-huaweicloud_v1.47.1 ~/.terraform.d/plugins/local-registry/huaweicloud/huaweicloud/1.47.1/linux_amd64/

                  
         git clone https://github.com/hbstarjason2021/terraform-workshop
         cd ./terraform-workshop/huaweicloud/ecs/
         
         #export hw_access_key=${{ secrets.HW_ACCESS_KEY }}
         #export hw_secret_key=${{ secrets.HW_SECRET_KEY }}
         
         export HW_ACCESS_KEY=${{ secrets.HW_ACCESS_KEY }}
         export HW_SECRET_KEY=${{ secrets.HW_SECRET_KEY }}
         
         # terraform fmt -check
         
         terraform init
         terraform validate -no-color
         terraform plan -no-color
         
         ## terraform apply -auto-approve
         
         
         
         
         
         
